name: 'Add new issue to project board'

on:
  issues:
    types:
    - opened
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: protecomp/ga-issues-projects@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        issue: ${{ github.event }}
